/*CADA CONSTANTE ES FIJA, ABSOLUTA. GUARDA Y NO CAMBIA. Y SE NOMBRAN EN MAYUSCULA */
export const GET_POKEMONS = 'GET_POKEMONS';     //I
export const GET_NAME_POKEMONS = 'GET_NAME_POKEMONS'; //VII
export const GET_DETAIL = 'GET_DETAIL'; //IX
export const POST_POKEMON = 'POST_POKEMON'; //VIII
export const GET_TYPES = 'GET_TYPES';           //IV
export const FILTER_POKEMONS_BY_TYPE = 'FILTER_BY_TYPE'; //II
export const FILTER_CREATED = 'FILTER_CREATED'; //III
export const ORDER_BY_ALPHABETICO = 'ORDER_BY_ALPHABETICO';   //V
export const ORDER_BY_ATTACK = 'ORDER_BY_ATTACK' //VI
